[[rules]]
id = "ignore-recaptcha-sitekey"
description = "Ignore Google reCAPTCHA sitekey"
regex = '''6LelWk4UAAAAAGaBJWFusnIlAVoaCK8DWnRBDE4g'''
tags = ["ignore"]

[[rules]]
id = "ignore-user-token"
description = "Ignore user-token example"
regex = '''026d0caed93471b507ed460ebddbd096'''
tags = ["ignore"]
